# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191202_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mail',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Срок выполнения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 3, 16, 22, 14, 403981), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 3, 16, 22, 14, 405000), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.TextField(verbose_name='Способ связи'),
        ),
    ]
