# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191124_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 17, 56, 5, 750802), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 17, 56, 5, 751800), verbose_name='Дата'),
        ),
    ]
